// Placeholder Firebase options for CI builds.
// In production, use the real firebase_options.dart generated by FlutterFire CLI:
//   dart run flutterfire_cli:flutterfire configure
//
// This file allows the app to compile in CI without real Firebase credentials.
// Firebase calls will fail at runtime — use a real config for device testing.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'cyberfit-placeholder',
    storageBucket: 'cyberfit-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'cyberfit-placeholder',
    storageBucket: 'cyberfit-placeholder.appspot.com',
    iosBundleId: 'com.cyberfit.app',
  );
}
